### ISSUE TITLE
Would be great if we could have an example using gulp as well

### ISSUE THREAD

**Issue by mitermayer** [lazd/karma-benchmark-example#1]
Example using gulp would be great :)

**Comment by lazd** [comment]
Here's a gulp example: https://github.com/lazd/karma-benchmark-example/tree/gulp

It's not as complete (no junit reporter etc, no separate tasks), but it should help you get going.

Note: as the guy that wrote the (arguably broken) [`gulp-karma`](https://github.com/lazd/gulp-karma), I **still** don't feel the [official method](https://github.com/karma-runner/gulp-karma) is gulp enough. I want to feed my list of benchmarks to Karma with gulp streams and globs, and I want to watch and execute runs with gulp's watch. The "official method" just says "launch Karma, let it handle globs for tests, let it handle watching when everything changes, and ignore gulp." As such, the gulp example is very boring because it literally uses absolutely nothing gulp has to offer.
